name: Auto SSL Certificate

on:
  schedule:
    - cron: '0 0 1,15 * *'  # 每月1日和15日尝试续期
  workflow_dispatch:

jobs:
  cert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Clone acme.sh
        run: |
          git clone https://github.com/acmesh-official/acme.sh.git ~/.acme.sh
          mkdir -p ~/.acme.sh/data

      - name: Set DNS credentials
        run: |
          echo "export CF_Key='${{ secrets.CF_API_KEY }}'" >> ~/.acme.sh/account.conf
          echo "export CF_Email='${{ secrets.CF_EMAIL }}'" >> ~/.acme.sh/account.conf

      - name: Issue certificate
        run: |
          ~/.acme.sh/acme.sh --issue --dns dns_cf \
            -d ${{ secrets.DOMAIN }} -d "*.${{ secrets.DOMAIN }}" \
            --keylength ec-256 \
            --server letsencrypt \
            --force

      - name: Install certificate to certs/
        run: |
          mkdir -p certs
          ~/.acme.sh/acme.sh --install-cert -d ${{ secrets.DOMAIN }} --ecc \
            --key-file       certs/privkey.pem \
            --fullchain-file certs/fullchain.pem \
            --ca-file        certs/ca.pem

      - name: Archive certificate
        run: |
          zip -r cert-${{ secrets.DOMAIN }}.zip certs

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: "SSLCert"
          files: cert.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
